### ISSUE TITLE
is this the best library in rust for low-latency channels? 

### ISSUE THREAD

**Issue by jonathanstrong** [johnshaw/magnetic#7]
This is the only channels library I have found that is touted as low latency (vs throughput). Based on the benchmarks in the code it is much faster than the std implementation. Do you have any more information about where this library stands compared to alternatives? It would also be very interesting to hear (or perhaps it already exists somewhere) what techniques you found most important in making this work faster. Thanks for any help you can provide and for publishing this code.

**Comment by johnshaw** [comment]
@jonathanstrong I have no idea how it compares to alternatives since I haven't surveyed the landscape of similar Rust libraries in quite some time. There was nothing similar available at the time I wrote it.

In general, the techniques I used are fairly standard (I think) in the lock-free queue space. There are a ton of resources on [the web](https://www.google.com/search?q=lock+free+queue) that can explain the inner workings much better than I could do here. I'm not sure if there is a good write-up for this specific algorithm, but once you figure out the basics, you should be able to understand the implementation I used.

**Comment by jonathanstrong** [comment]
thanks - I will do some reading. The main issue is, Rust is the first systems language I have written extensively in and the code here is a completely different style than I am used to. For instance, I have never come across a problem (yet) that required the use of "raw" pointers. But the thing about making computers go fast is, eventually your tolerance starts to increase and you have to up your dosage haha. Thanks for your quick reply.
